### ISSUE TITLE
Submit Lewis' paperwork to HR

### ISSUE THREAD

**Issue by z3cka** [UCLALibrary/iOSLibraryAppVersion2#2]
I've told HR that you (@lewishong) are a new student hire. The next step is to fill out the paperwork and go into HR to make it official.

Any questions, hit me on #Slack.

**Comment by z3cka** [comment]
Hey @lewishong, I finally had my meeting with HR. Please visit https://www.library.ucla.edu/about/jobs-ucla-library/student-jobs/new-student-hires so you can fill out the paperwork prior to going to the HR office. I think you can stop by HR any time with the all the requirements mentioned at the link above.

Let me know if you have any questions on the process... I'm learning it as well and still have one more supervisor training to attend.

**Comment by z3cka** [comment]
assigning this to @lewishong

**Comment by lewishong** [comment]
submitted all my paperwork but still can't access trs

**Comment by z3cka** [comment]
hey @lewishong yes, HR is still processing; we are figuring out what the project code is. you will be in the system soon. Thanks for your patience.

**Comment by z3cka** [comment]
@lewishong please close the issue when you are able to see your timesheet in TRS. Thanks.

**Comment by lewishong** [comment]
@z3cka looks like I'm officially in the system!

**Comment by lewishong** [comment]
@z3cka I'm getting this error message on TRS
Alert: Errors found 
Primary supervisor is not set up for your assignment. Please contact your Department Payroll Officer for assistance.

**Comment by z3cka** [comment]
I've emailed HR, will update when I hear back.

**Comment by lewishong** [comment]
I think everything is working now
