### ISSUE TITLE
Schedule Bi-weekly check-in meeting

### ISSUE THREAD

**Issue by z3cka** [UCLALibrary/iOSLibraryAppVersion2#3]
What day and time did we decide on for meeting?

**Comment by z3cka** [comment]
I think we said Thursdays, starting next week... what time? I can't find it in my notes.

**Comment by z3cka** [comment]
This will be a remote meeting via Google Hangouts, but you  two are welcome to meet in-person if needed.

**Comment by z3cka** [comment]
How about 1pm via Hangouts?

**Comment by lewishong** [comment]
Yeah this sounds good to me. Sorry I didn't reply to this. I'm still getting used to everything on github so I didn't see this.

**Comment by z3cka** [comment]
@lewishong no worries, thanks for the response. will send calendar invite tomorrow.

**Comment by z3cka** [comment]
here is the url meeting that we will use each time: https://hangouts.google.com/hangouts/_/g.ucla.edu/cgrzecka

I'm not sure if I have to initiate it each time or not... we will see.
