### ISSUE TITLE
Patrick, Get local dev environment setup

### ISSUE THREAD

**Issue by z3cka** [UCLALibrary/iOSLibraryAppVersion2#5]
Get the app running locally in iOS Simulator and are able to make basic changes.

**Comment by z3cka** [comment]
I'd like to get some documentation on this.

**Comment by lewishong** [comment]
Was able to get the project files to come together on xcode but ran into a good number of buildtime errors so am currently working so that I can run and make basic changes.
Working out of Big Nerd Ranch book. Currently learning about model/view controller.

**Comment by z3cka** [comment]
with regards to documentation, take a look at https://github.com/UCLALibrary/UCLA_Library_Android_Studio/blob/master/README.md _(if you have access)_ 

## Here is a good guide for writing good READMEs
http://stackoverflow.com/questions/2304863/how-to-write-a-good-readme

**Comment by lewishong** [comment]
got the project to run locally. everything seems to work on version 8.0 of XCode but on newer versions of XCode the map doesn't fit the screen correctly

**Comment by z3cka** [comment]
@shihpatrick here is a good place to start.
